### PR TITLE
Add dynamic inspect and query commands

### PR DESCRIPTION
**Pull request by mark-rushakoff**
These new commands use the protoreflect third-party library.

The inspect subcommand lets you explore available services and their
associated message types on a remote chain.

The query subcommand lets you send arbitrary messages to specific gRPC
services on a remote chain. It accepts JSON-formatted messages at the
command line; then converts them to protobuf internally, sends them to
the server, receives a protobuf response and formats it as JSON on
stdout.

### CODE REVIEW

**Comment by jackzampolin** [comment]
Panic when `lens dyn i cosmoshub`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x103087578]

goroutine 1 [running]:
github.com/jhump/protoreflect/desc.(*ServiceDescriptor).GetFullyQualifiedName(...)
	/Users/johnzampolin/go/pkg/mod/github.com/jhump/protoreflect@v1.12.0/desc/descriptor.go:1353
github.com/strangelove-ventures/lens/cmd.dynamicInspect(0x14000eb8a00, 0x14000141f80, {0x14000ed31e0, 0x1b}, {0x0, 0x0}, {0x0, 0x0})
	/Users/johnzampolin/go/src/github.com/strangelove-ventures/lens/cmd/dynamic.go:252 +0x1738
github.com/strangelove-ventures/lens/cmd.dynInspectCmd.func1(0x14000eb8a00, {0x14000eb4290, 0x1, 0x1})
	/Users/johnzampolin/go/src/github.com/strangelove-ventures/lens/cmd/dynamic.go:216 +0x1d0
github.com/spf13/cobra.(*Command).execute(0x14000eb8a00, {0x14000eb4270, 0x1, 0x1})
	/Users/johnzampolin/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x14000e29680)
	/Users/johnzampolin/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/johnzampolin/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/strangelove-ventures/lens/cmd.Execute()
	/Users/johnzampolin/go/src/github.com/strangelove-ventures/lens/cmd/root.go:130 +0x78
main.main()
	/Users/johnzampolin/go/src/github.com/strangelove-ventures/lens/main.go:23 +0x20
```

**Comment by mark-rushakoff** [comment]
Thanks @jackzampolin, I just pushed commit b0f52bf0e3adbfa5ab8d31fd3b3102822e834711 which should fix the cosmoshub error. Can you share the gRPC address you're using for `osmosis`?

**Comment by mark-rushakoff** [comment]
I am fairly convinced this is a bug in one of the libraries we're using.

You get the same error  if you request a single proposal: `lens dyn q osmosis.strange.love:9090 cosmos.gov.v1beta1.Query Proposals '{"pagination": {"limit":1}}'`.

The binary content of that response, base64-encoded, is

`CtADCAESwAIKIC9jb3Ntb3MuZ292LnYxYmV0YTEuVGV4dFByb3Bvc2FsEpsCCiNXZSB3YW50IHRvIGNsYWltIHJld2FyZHMgY29tcGxldGVseRLzAVJld2FyZC1jbGFpbWluZyB0ZXh0IHByb3Bvc2FsCgpQbGVhc2UgZGVwb3NpdCBhbmQgdm90ZSBmb3IgdGhpcyBwcm9wb3NhbCBpZiB5b3Ugd2FudCB0byBjb21wbGV0ZSAxMDAlIG9mIHlvdXIgZHJvcCBjaGFsbGVuZ2UgQVNBUC4KClRoYW5rcyBPc21vc2lzIHRlYW0gZm9yIEtZQy1mcmVlIGFuZCBuby1idWxsc2hpdCBkcm9wLgpMZXRzIGJ1aWxkIHRoZSBzdHJvbmcgY29tbXVuaXR5IGFuZCBiZXR0ZXIgd2ViIHRvZ2V0aGVyIRgDIjoKDTQ0ODE5NjA0MzQ2NjYSDTEzNzE3MTc1ODE5MjQaDDYxNjAzNTcwOTk0MiIMMTEwMDYwNjYwNDI3KgwIuIe5hgYQtoCb6AEyDAi48YKHBhC2gJvoAToTCgV1b3NtbxIKMjUxMDAwMDAwMEIMCMrguYYGEJT7/aADSgwIysnJhgYQlPv9oAMSCgoIAAAAAAAAAAI=`.

You can paste that into online protobuf decoders, e.g. https://protobuf-decoder.netlify.app/, and it decodes correctly.

You can modify the lens code to text-marshal it instead of JSON-marshalling, and it works successfully:

```
proposals:<proposal_id:1 content:<type_url:"/cosmos.gov.v1beta1.TextProposal" value:"\n#We want to claim rewards completely\022\363\001Reward-claiming text proposal\n\nPlease deposit and vote for this proposal if you want to complete 100% of your drop challenge ASAP.\n\nThanks Osmosis team for KYC-free and no-bullshit drop.\nLets build the strong community and better web together!" > status:PROPOSAL_STATUS_PASSED final_tally_result:<yes:"4481960434666" abstain:"1371717581924" no:"616035709942" no_with_veto:"110060660427"> submit_time:<seconds:1624130488 nanos:486981686 > deposit_end_time:<seconds:1625340088 nanos:486981686 > total_deposit:<denom:"uosmo" amount:"2510000000"> voting_start_time:<seconds:1624141898 nanos:874478996 > voting_end_time:<seconds:1624401098 nanos:874478996 >> pagination:<next_key:"\000\000\000\000\000\000\000\002">
```

It is only when we attempt to JSON-marshal it, that we hit this panic. I'll continue reducing the test case tomorrow, and may end up filing an issue upstream.

**Comment by jackzampolin** [comment]
This may be an issue with chain side implementation too.

**Comment by mark-rushakoff** [comment]
I filed https://github.com/jhump/protoreflect/issues/507 and made a standalone reproducer at https://github.com/mark-rushakoff/protoreflect-json-marshal-any-repro. I have a couple more leads I can try on working around this in the meantime.

**Comment by jackzampolin** [comment]
We should prob merge this in anticipation of other work here. been sharing this with a number of folks

**Pull request merged**
